### PR TITLE
Add tests for duration()

### PR DESCRIPTION
**Pull request by parulsingh23**
Added basic usage tests for duration(), as well as tests for the terms parameter. 
I have a question, however, on whether duration(3600001,2) (which should return an array), will return ["1 hour", "1 ms"], or "1 hour, 1 ms".

### CODE REVIEW

**Comment by LeaVerou** [comment]
Wait, `duration(3600001,2)` should return one term only, since hours and ms are not consecutive!

**Comment by parulsingh23** [comment]
I fixed the duration tests to make sure only consecutive terms are in the array if a number of terms parameter is specified.

**Comment by parulsingh23** [comment]
@LeaVerou you can review this.

**Comment by LeaVerou** [comment]
LGTM. I would suggest making the numbers of ms a calculation, to make it obvious what they are to someone reading the tests (e.g. instead of `3600000`, you could write `60 * 60 * 1000`)

**Comment by parulsingh23** [comment]
@LeaVerou you can look this over, I
-  Updated tests to make the calculations easier to read as mentioned above
- Added tests for new duration feature of list of units in place of number of terms,
   Some key things I wanted to clarify for this list of units params:
   - Any time units provided that amount to 0 are not returned, so 
         • duration(0, ["hours"]) is [] 
         • duration(1, ["hours"]) is []
         • duration(60*60*1000, ["weeks", "hours", "minutes"]) is [“1 hour”]
   - We can have nonconsecutive time units returned, so
         • duration(60*60*1000+1, ["hours","ms"]) is ["1 hour", "1 ms"])

**Comment by parulsingh23** [comment]
@LeaVerou you can look over; it has the tests for just the number of terms param in the duration function

**Review by LeaVerou — APPROVED** [review]

**Pull request merged**
